TCC/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

cadastros/urls.py
from django.urls import path 

from .views import EstadoCreate, CidadeCreate, EmpresaCreate, PropriedadeCreate, ServicoCreate, ContratoCreate, ConfiguracaoSistemaCreate
from .views import EmpresaUpdate, PropriedadeUpdate, ServicoUpdate, EstadoUpdate, CidadeUpdate, ContratoUpdate
from .views import EstadoList, CidadeList, EmpresaList, PropriedadeList, ServicoList, ContratoList
from .views import EstadoDelete, CidadeDelete, EmpresaDelete, PropriedadeDelete, ServicoDelete
from .views import ContratoDetailView, EmpresaDetailView

urlpatterns = [
    path('cadastros/contrato', ContratoCreate.as_view(), name = "cadastro-contrato"),
    path('cadastros/estado', EstadoCreate.as_view(), name = "cadastro-estado"),
    path('cadastros/cidade', CidadeCreate.as_view(), name = "cadastro-cidade"),           
    path('cadastros/empresa/', EmpresaCreate.as_view(), name ="cadastro-empresa"),
    path('cadastros/propriedade/', PropriedadeCreate.as_view(), name ="cadastro-propriedade"),
    path('cadastros/servico/', ServicoCreate.as_view(), name ="cadastro-servico"),
    path('cadastros/sistema/', ConfiguracaoSistemaCreate.as_view(), name ="cadastro-sistema"),


    path('editar/estado/<int:pk>', EstadoUpdate.as_view(), name ="editar-estado"),
    path('editar/cidade/<int:pk>', CidadeUpdate.as_view(), name ="editar-cidade"),
    path('editar/empresa/<int:pk>', EmpresaUpdate.as_view(), name ="editar-empresa"),    
    path('editar/propriedade/<int:pk>', PropriedadeUpdate.as_view(), name ="editar-propriedade"),
    path('editar/servico/<int:pk>', ServicoUpdate.as_view(), name ="editar-servico"),
    path('editar/contrato/<int:pk>', ContratoUpdate.as_view(), name ="editar-contrato"),
    



    path('excluir/estado/<int:pk>', EstadoDelete.as_view(), name="excluir-estado"),
    path('excluir/cidade/<int:pk>', CidadeDelete.as_view(), name="excluir-cidade"),
    path('excluir/propriedade/<int:pk>', PropriedadeDelete.as_view(), name="excluir-propriedade"),
    path('excluir/Empresa/<int:pk>', EmpresaDelete.as_view(), name="excluir-empresa"),
    path('excluir/servico/<int:pk>', ServicoDelete.as_view(), name="excluir-servico"),




    path('listar/estado/', EstadoList.as_view(), name="listar-estado"),
    path('listar/cidade/', CidadeList.as_view(), name="listar-cidade"),
    path('listar/empresa/', EmpresaList.as_view(), name="listar-empresa"),
    path('listar/propriedade/', PropriedadeList.as_view(), name="listar-propriedade"),
    path('listar/servico/', ServicoList.as_view(), name="listar-servico"),
    path('listar/contrato/', ContratoList.as_view(), name="listar-contrato"),

    path('detail/contrato/<int:pk>', ContratoDetailView.as_view(), name="detail-contrato"),
    path('detail/empresa/<int:pk>', EmpresaDetailView.as_view(), name="detail-empresa"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.


class Estado(models.Model):
    sigla = models.CharField(max_length=2)
    nome = models.CharField(max_length=50, verbose_name="nome do estado")

    def __str__(self):
        return "{} ({})".format(self.sigla, self.nome)

class Cidade(models.Model):
    nome = models.CharField(max_length=50)
    estado = models.ForeignKey(Estado, on_delete=models.PROTECT)
   

    def __str__(self):
        return self.nome + '/' + self.estado.sigla

class Servico(models.Model):
    descricao_servico = models.CharField(max_length=100 )
    valor = models.CharField(max_length=9)

    def  __str__(self):
            return "{} ({})".format(self.descricao_servico, self.valor)

class Empresa(models.Model):
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT)
    nome_proprietario = models.CharField(max_length=100)
    cpf = models.CharField(max_length=14, unique=True )
    rg = models.CharField(max_length=15, unique=True)
    razao_social = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=18, unique=True, verbose_name="CNPJ")
    inscricao_estadual = models.CharField(max_length=45, verbose_name="Inscrição Estadual")
    endereco = models.CharField(max_length=100)

    def __str__(self):
        return "{} ({})".format(self.nome_proprietario, self.cpf, self.cnpj, 
                self.razao_social, self.cnpj, self.inscricao_estadual, self.endereco)

class Propriedade(models.Model):
    nome_propriedade = models.CharField(max_length=45)
    endereco = models.CharField(max_length=100)
    area_propriedade = models.CharField(max_length=45)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT)
    empresa = models.ForeignKey(Empresa, on_delete= models.PROTECT)

    def __str__(self):
        return "{} ({})".format(self.nome_propriedade, self.endereco, self.area_propriedade, self.cidade, self.empresa)


class ConfiguracaoSistema(models.Model):
    razao_social = models.CharField(max_length=100)
    nome_fantasia = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=100)
    inscricao_estadual = models.CharField(max_length=100)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT)
    endereco = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    cep = models.CharField(max_length=8)
    email = models.CharField(max_length=100)

    def __str__(self):
        return "{} ({})".format(self.razao_social, self.nome_fantasia, self.cnpj, self.inscricao_estadual, self.cidade,
        self.endereco, self.bairro, self.cep, self.email)

class Contrato(models.Model):
    servico = models.ForeignKey(Servico, on_delete= models.PROTECT)
    propriedade = models.ForeignKey(Propriedade, on_delete= models.PROTECT)
    data_inicial = models.DateField(default=date.today)
    data_final = models.DateField(default=date.today)
    registrado_por = models.ForeignKey(User, on_delete= models.PROTECT)
    registrado_em = models.DateField(auto_now=True)
    contratante = models.ForeignKey(Empresa, on_delete= models.PROTECT)
    contratada = models.ForeignKey(ConfiguracaoSistema, on_delete= models.PROTECT)
    cidade = models.ForeignKey(Cidade, on_delete= models.PROTECT)
    

cadastros/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.detail import DetailView

from .models import *

from django.views.generic.list import ListView

from django.urls import reverse_lazy


class EstadoCreate(LoginRequiredMixin, CreateView):
    model = Estado
    fields = ['sigla', 'nome']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-estado')

    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Cadastro de Estado"
            context['botao'] = "Cadastrar"
            context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

            return context


class CidadeCreate(LoginRequiredMixin, CreateView):
    model = Cidade
    fields = ['nome', 'estado']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-cidade')


def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Cadastro de Cidade"
            context['botao'] = "Cadastrar"
            context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

            return context


class ServicoCreate(LoginRequiredMixin, CreateView):
    model = Servico
    fields = ['descricao_servico', 'valor']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-servico')

    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Cadastro de Serviço"
            context['botao'] = "Cadastrar"
            context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

            return context


class EmpresaCreate(LoginRequiredMixin, CreateView):
    model = Empresa
    fields = ['cidade','nome_proprietario', 'cpf', 'rg', 'razao_social', 'cnpj',
        'inscricao_estadual', 'endereco']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-empresa')

    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Cadastro de Empresa"
            context['botao'] = "Cadastrar"

            return context


class PropriedadeCreate(LoginRequiredMixin, CreateView):
    model = Propriedade
    fields = ['nome_propriedade', 'endereco', 'area_propriedade', 'cidade', 'empresa']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-propriedade')

    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Cadastro de Propriedade"
            context['botao'] = "Cadastrar"
            context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'
            return context

class ContratoCreate(LoginRequiredMixin, CreateView):
    model = Contrato
    fields = ["cidade", "servico", "propriedade", "registrado_por", "data_inicial", 
                "data_final", "contratante", "contratada"]    
    template_name = 'cadastros/contrato.html'
    success_url = reverse_lazy('listar-contrato')

    def form_valid(self, form):

        # Define o usuário como usuário logado
        form.instance.registrado_por = self.request.user
        
        url = super().form_valid(form)

        return url
        
class ConfiguracaoSistemaCreate(LoginRequiredMixin, CreateView):
    model = ConfiguracaoSistema
    fields = ['razao_social', 'nome_fantasia', 'cnpj',
        'inscricao_estadual', 'cidade', 'endereco', 'bairro', 'cep', 'email']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')


    def get_context_data(self, *args, **kwargs):
            context = super().get_context_data(*args, **kwargs)

            context['titulo'] = "Configuração sistema"
            context['botao'] = "Cadastrar"

            return context

######################## UPDATE #######################

class EstadoUpdate(LoginRequiredMixin, UpdateView):
    model = Estado
    fields = ['sigla', 'nome']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy("listar-estado")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de Estados"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'
        return context

class CidadeUpdate(LoginRequiredMixin, UpdateView):
    model = Cidade
    fields = ['nome']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy("listar-cidade")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de Cidades"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context

class ServicoUpdate(LoginRequiredMixin, UpdateView):
    model = Servico
    fields = ['descricao_servico', 'valor']
    template_name ='cadastros/form.html'
    success_url = reverse_lazy('listar-servico')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de Servicos"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'
        return context

class EmpresaUpdate(LoginRequiredMixin, UpdateView):
    model = Empresa
    fields = ['cidade','nome_proprietario', 'cpf', 'rg', 'razao_social', 'cnpj', 'inscricao_estadual', 'endereco']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-empresa')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de Empresas"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context

class PropriedadeUpdate(LoginRequiredMixin, UpdateView):
    model = Propriedade
    fields =['nome_propriedade', 'endereco', 'area_propriedade', 'cidade', 'empresa']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-propriedade')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de Propriedades"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'
        return context

class ContratoUpdate(LoginRequiredMixin, UpdateView):
    model = Contrato
    fields = ['cidade','servico', "propriedade", "data_inicial", "data_final", "contratante"]    
    template_name = 'cadastros/contrato.html'
    success_url = reverse_lazy('listar-contrato')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['titulo'] = "Cadastro de contrato"
        context['botao'] = "Atualizar"
        context['icone'] = '<i class="fa fa-check" aria-hidden="true"></i>'

        return context

######################## DELETE #######################
class EstadoDelete(LoginRequiredMixin, DeleteView):
    model = Estado
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-estado')


class CidadeDelete(LoginRequiredMixin, DeleteView):
    model = Cidade
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-cidade')

class ServicoDelete(LoginRequiredMixin, DeleteView):
    model = Servico
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-servico')

class EmpresaDelete(LoginRequiredMixin, DeleteView):
    model = Empresa
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-empresa')

class PropriedadeDelete(LoginRequiredMixin, DeleteView):
    model = Propriedade
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-propriedade')

##########################listView#######################

class EstadoList(LoginRequiredMixin, ListView):
    model = Estado
    template_name = 'cadastros/listar/estado.html'

class CidadeList(LoginRequiredMixin, ListView):
    model = Cidade
    template_name = 'cadastros/listar/cidade.html'

class ServicoList(LoginRequiredMixin, ListView):
    model = Servico
    template_name = 'cadastros/listar/servico.html'

class EmpresaList(LoginRequiredMixin, ListView):
    model= Empresa
    template_name = 'cadastros/listar/empresa.html'

class PropriedadeList(LoginRequiredMixin, ListView):
    model = Propriedade
    template_name = 'cadastros/listar/propriedade.html'

class ContratoList(LoginRequiredMixin, ListView):
    model = Contrato
    template_name = 'cadastros/listar/contrato_list.html'


###################DetailView#########################

class ContratoDetailView(LoginRequiredMixin, DetailView):
    model = Contrato
    template_name = 'cadastros/detalhe/contrato.html' # Arrumei aqui para o arquivo certo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class EmpresaDetailView(LoginRequiredMixin, DetailView):
    model = Empresa
    template_name = 'cadastros/detalhe/empresa.html' # Arrumei aqui para o arquivo certo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

cadastros/templates/cadastros/agenda.html
{% extends 'paginas/modelo.html'%}

{% block titulo %}
<title>Cadastro</title>
{% endblock%}

{% block conteudo %}
    <div class="container ">
       <div id="calendar"></div>
    </div>
{% endblock %}

cadastros/templates/cadastros/contrato.html
{% extends 'paginas/modelo.html'%}

{% load static %}

{% load crispy_forms_tags %}

{% block titulo %}
<title>Cadastro de contrato</title>

{% endblock%}

{% block conteudo %}

        <div class="col">
            <div class="card format container-fluid shadow p-3 mb-5 bg-white rounded">
                <div class="card-body">
                    <h1>Contratos </h1>
                    <p class="lead">
                        preencha todos os campos dos contratos
                    </p>
                    <hr>
                    <form action="" method="POST">
                        <div class="row">
                            <div class="col">
                                {% csrf_token %}
                            </div>
                        </div>

                        {{form|crispy}}

                        <button type="submit" class="btn btn-primary"> Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



</div>

{% endblock %}

{% block rodape %}

{% endblock %}

cadastros/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo.html'  %}

{% load static %}

{% block conteudo %}
    <div class="container ">
        <div class="card shadow-lg p-3 mb-5 bg-white rounded">
            <div class="card-body">
                <p class="lead">
                    confirme para excluir o registro 

                </p>
                <form action="" method="post">
                    <p>Deseja excluir o registro: <strong>{{ object }}</strong></p>
                        {% csrf_token %}
                           
                        {{form.as_p}}
                                
                    <button type="submit" class="btn btn-danger"> excluir</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo.html'%}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="container ">
    <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h1>{{ titulo }} </h1>
            <p class="lead">
                preencha todos os campos obrigatorios
            </p>
            <hr>
            <form action="" method="POST">
                <div class="row">
                    <div class="col">
                        {% csrf_token %}
                    </div>
                </div>

                {{form|crispy}}

                <button type="submit" class="btn btn-primary"> Cadastrar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    
    <script>
        $(document).ready(function(){
            
            $("#id_data").mask("00/00/0000");
            $("#id_cpf").mask("000.000.000-00");
            $("#id_cnpj").mask('00.000.000/0000-00');
            $("#id_valor").mask("R$0000,00");
            $("#id_rg").mask("000000000-0");

        });
    </script>
{% endblock %}

cadastros/templates/cadastros/form_update.html
{% extends 'paginas/modelo.html'%}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="container ">
    <div class="card shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-body">
            <h1>{{ }} </h1>
            <p class="lead">
                preencha todos os campos obrigatorios
            </p>
            <hr>
            <form action="" method="POST">
                <div class="row">
                    <div class="col">
                        {% csrf_token %}
                    </div>
                </div>

                {{form|crispy}}

                <button type="submit" class="btn btn-primary"> Cadastrar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function () {

        $("#id_data").mask("00/00/0000");
        $("#id_cpf").mask("0000.000.000-00");
        $("#id_cnpj").mask('00.000.000/0000-00');
        $("#id_valor").mask("R$0000.00");
    });
</script>
{% endblock %}

cadastros/templates/cadastros/index.html
{% extends 'paginas/modelo.html'%}

{% load static %}

cadastros/templates/cadastros/modelo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    {% block titulo %}
    <title>Dashboard - SB Admin</title>
    {% endblock %}

    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap4.min.css' %}" rel="stylesheet" crossorigin="anonymous" />
    <script src="{% static '/js/all.min.js' %}" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    {% block menu %}
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">
        <a class="navbar-brand" href="index.html">GerCont</a><button class="btn btn-link btn-sm order-1 order-lg-0"
            id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search"
                    aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="login.html">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    {% endblock %}
    {% block sidenav %}
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="layout-static.html">Static
                                    Navigation</a><a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                            aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            cadastros

                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                               <a class="nav-link collapsed" id="collapsePages" data-toggle="collapse" data-target="#collapsePages"
                                    aria-expanded="false" aria-controls="collapsePages" href="">
                                <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                                    clientes
                               </a>
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div></a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"
                                    data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link"
                                            href="login.html">Login</a><a class="nav-link"
                                            href="register.html">Register</a><a class="nav-link"
                                            href="password.html">Forgot Password</a></nav>
                                </div>
                                
                            </nav>
                        </div>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    GerCont
                </div>
            </nav>
            {% endblock %}
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                {% block conteudo%}
                    <h1>teste</h1>
                {% endblock %}
            </main>
            {% block rodape %}
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
            {% endblock %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/Chart.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.dataTables.min.js'%}" crossorigin="anonymous"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}" crossorigin="anonymous"></script>
</body>

</html>